# Generated by Django 5.1.3 on 2024-11-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(verbose_name=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('id_producto', models.CharField(max_length=11)),
                ('id_empleado', models.CharField(max_length=11)),
                ('id_cliente', models.CharField(max_length=11)),
            ],
        ),
    ]
